# Generated by Django 5.2.8 on 2026-01-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_update_booking_and_add_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user_email',
            field=models.EmailField(db_index=True, default='guest@example.com', help_text='Guest email used for OTP access', max_length=254),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_name',
            field=models.CharField(default='Guest', help_text='Guest full name', max_length=150),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_phone',
            field=models.CharField(blank=True, help_text='Optional phone number', max_length=30, null=True),
        ),
    ]
