# Generated by Django 5.2.8 on 2025-11-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='room',
            name='available_rooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='bed_type',
            field=models.CharField(choices=[('king', 'King'), ('queen', 'Queen'), ('twin', 'Twin Bed'), ('single', 'Single Bed')], default='king', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='free_cancellation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='is_refundable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='size_in_sqft',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='room',
            name='total_rooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('deluxe', 'Deluxe'), ('suite', 'Suite'), ('family', 'Family'), ('premium', 'Premium')], max_length=20),
        ),
    ]
