# Generated by Django 5.2.8 on 2025-11-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_room_amenities_room_available_rooms_room_bed_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='max_guests',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('deluxe', 'Deluxe'), ('suite', 'Suite'), ('family', 'Family'), ('premium', 'Premium')], max_length=20, null=True),
        ),
    ]
