# Generated by Django 5.2.8 on 2025-11-30 16:00

from django.db import migrations, models


def populate_room_names(apps, schema_editor):
    """Populate blank room_names with a default value based on room_type or a generic name."""
    Room = apps.get_model('hotels', 'Room')
    ROOM_TYPES_DICT = {
        'standard': 'Standard',
        'deluxe': 'Deluxe',
        'suite': 'Suite',
        'family': 'Family',
        'premium': 'Premium',
    }
    for room in Room.objects.filter(room_name=''):
        if room.room_type:
            # Use room_type to create a name like "Standard Room", "Deluxe Room", etc.
            room_type_display = ROOM_TYPES_DICT.get(room.room_type, room.room_type.title())
            room.room_name = f"{room_type_display} Room"
        else:
            # Generic name if no room_type
            room.room_name = f"Room {room.id}"
        room.save()


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_alter_room_max_guests_alter_room_price_per_night_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_room_names, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(max_length=255),
        ),
    ]
