# Generated by Django 5.2.8 on 2025-01-27 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_alter_room_room_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_rooms', models.IntegerField()),
                ('booked_rooms', models.IntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='hotels.room')),
            ],
            options={
                'verbose_name_plural': 'Room Inventories',
                'ordering': ['date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='roominventory',
            unique_together={('room', 'date')},
        ),
    ]

