# Generated by Django 5.2.8 on 2025-01-27 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_roominventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('duration_nights', models.IntegerField(default=1)),
                ('includes_meals', models.BooleanField(default=False)),
                ('includes_activities', models.BooleanField(default=False)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='hotels.hotel')),
            ],
            options={
                'verbose_name_plural': 'Packages',
                'ordering': ['-created_at'],
            },
        ),
    ]

