# Generated by Django 5.2.8 on 2026-01-14 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roominventory',
            name='booked_rooms',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='roominventory',
            name='total_rooms',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
