# Generated by Django 5.2.8 on 2026-01-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_hotelimage_roomimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_adults',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='room',
            name='max_children',
            field=models.IntegerField(default=1),
        ),
    ]
