# Generated by Django 5.2.8 on 2026-01-18 15:16

import django.core.validators
import hotels.image_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_room_max_adults_room_max_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelimage',
            name='image',
            field=models.ImageField(upload_to=hotels.image_models.hotel_image_path, validators=[hotels.image_models.validate_image_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'heic', 'avif'])]),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(upload_to=hotels.image_models.room_image_path, validators=[hotels.image_models.validate_image_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'heic', 'avif'])]),
        ),
    ]
