# Generated by Django 5.2.8 on 2026-02-11 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0011_alter_hotelimage_image_alter_roomimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='hotels.room'),
        ),
    ]
